from domain.configuration.input_configuration import InputConfiguration
from domain.configuration.output_configuration import OutputConfiguration
from domain.configuration.run_configuration_generator import RunConfigurationGenerator